namespace LaciSynchroni.Shared.Metrics;

public class MetricsAPI
{
    public const string CounterInitializedConnections = "laci_initialized_connections";
    public const string GaugeConnections = "laci_connections";
    public const string GaugeAuthorizedConnections = "laci_authorized_connections";
    public const string GaugeAvailableWorkerThreads = "laci_available_threadpool";
    public const string GaugeAvailableIOWorkerThreads = "laci_available_threadpool_io";
    public const string GaugeUsersRegistered = "laci_users_registered";
    public const string CounterUsersRegisteredDeleted = "laci_users_registered_deleted";
    public const string GaugePairs = "laci_pairs";
    public const string GaugePairsPaused = "laci_pairs_paused";
    public const string GaugeFilesTotal = "laci_files";
    public const string GaugeFilesTotalColdStorage = "laci_files_cold";
    public const string GaugeFilesTotalSize = "laci_files_size";
    public const string GaugeFilesTotalSizeColdStorage = "laci_files_size_cold";
    public const string GaugeFilesDownloadingFromCache = "laci_files_downloading_from_cache";
    public const string GaugeFilesTasksWaitingForDownloadFromCache = "laci_files_waiting_for_dl";
    public const string CounterUserPushData = "laci_user_push";
    public const string CounterUserPushDataTo = "laci_user_push_to";
    public const string CounterAuthenticationRequests = "laci_auth_requests";
    public const string CounterAuthenticationCacheHits = "laci_auth_requests_cachehit";
    public const string CounterAuthenticationFailures = "laci_auth_requests_fail";
    public const string CounterAuthenticationSuccesses = "laci_auth_requests_success";
    public const string GaugeAuthenticationCacheEntries = "laci_auth_cache";
    public const string GaugeGroups = "laci_groups";
    public const string GaugeGroupPairs = "laci_groups_pairs";
    public const string GaugeFilesUniquePastHour = "laci_files_unique_past_hour";
    public const string GaugeFilesUniquePastHourSize = "laci_files_unique_past_hour_size";
    public const string GaugeFilesUniquePastDay = "laci_files_unique_past_day";
    public const string GaugeFilesUniquePastDaySize = "laci_files_unique_past_day_size";
    public const string GaugeCurrentDownloads = "laci_current_downloads";
    public const string GaugeQueueFree = "laci_download_queue_free";
    public const string GaugeQueueActive = "laci_download_queue_active";
    public const string GaugeQueueInactive = "laci_download_queue_inactive";
    public const string GaugeDownloadQueue = "laci_download_queue";
    public const string GaugeDownloadQueueCancelled = "laci_download_queue_cancelled";
    public const string GaugeDownloadPriorityQueue = "laci_download_priority_queue";
    public const string GaugeDownloadPriorityQueueCancelled = "laci_download_priority_queue_cancelled";
    public const string CounterFileRequests = "laci_files_requests";
    public const string CounterFileRequestSize = "laci_files_request_size";
    public const string CounterUserPairCacheHit = "laci_pairscache_hit";
    public const string CounterUserPairCacheMiss = "laci_pairscache_miss";
    public const string GaugeUserPairCacheUsers = "laci_pairscache_users";
    public const string GaugeUserPairCacheEntries = "laci_pairscache_entries";
    public const string CounterUserPairCacheNewEntries = "laci_pairscache_new_entries";
    public const string CounterUserPairCacheUpdatedEntries = "laci_pairscache_updated_entries";
    public const string GaugeGposeLobbies = "laci_gpose_lobbies";
    public const string GaugeGposeLobbyUsers = "laci_gpose_lobby_users";
    public const string GaugeHubConcurrency = "laci_free_concurrent_hub_calls";
    public const string GaugeHubQueuedConcurrency = "laci_free_concurrent_queued_hub_calls";
}