name: Build Laci Services

on:
  push:
    tags:
      # Only trigger on semantic version tags with 'v' prefix
      - 'v[0-9]+.[0-9]+.[0-9]+*'

# Explicit permissions for security
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Matrix strategy to build multiple images
    strategy:
      matrix:
        service:
          - name: server
            
          - name: authservice
          - name: staticfilesserver
          - name: services

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # Load submodules
          submodules: 'recursive'
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for ${{ matrix.service.name }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/laci-server/${{ matrix.service.name }}
          tags: |
            # Strip 'v' prefix from version tags: v1.2.3 -> 1.2.3
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}},enable={{is_default}}
            type=raw,value=latest,enable={{is_default && is_default_branch}}
      
      - name: Build and push ${{ matrix.service.name }}
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          target: ${{ matrix.service.name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.service.name }}
          cache-to: type=gha,mode=max,scope=${{ matrix.service.name }}
          platforms: linux/amd64
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/laci-server/${{ matrix.service.name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
